### ISSUE TITLE
Copy to Clipboard seems to be broken

### ISSUE THREAD

**Issue by pikapictured** [PoomSmart/YTMABConfig#1]
A/B settings are working fine, including Import and seeing the state of the A/B settings. Clicking on copy causes the app to crash.

Thanks for the support! ❤️

Here's the logs and screen recording:

https://github.com/user-attachments/assets/7063adc6-3bbd-48de-885b-1497886f88db

![YouTubeMusic.txt](https://github.com/user-attachments/files/17580446/YouTubeMusic-2024-10-30-203212.txt)

**Comment by PoomSmart** [comment]
Fixed in v1.0.1
